--------------Creating tumour Table ---------------------------------------
CREATE TABLE IF NOT EXISTS {SOURCE_SCHEMA}.tumour (
	e_patid					bigint,
	e_cr_patid				bigint,
	e_cr_id					bigint,
	ethnicity				varchar(10),
	ethnicityname			varchar(35),
	diagnosisdatebest		date,	
	diagnosisdateflag		smallint,
	basisofdiagnosis		smallint,
	site_icd10_o2			varchar(5),
	site_icd10_o2_3char		varchar(5),
	morph_icd10_o2			int,
	behaviour_icd10_o2		varchar(20),
	site_coded_3char		varchar(5),
	coding_system			smallint,
	coding_system_desc		varchar(20),	
	morph_coded				varchar(10),
	behaviour_coded			varchar(5), --- This attribute has a Field type of NUMBER in the Cancer Registration Data Dictionary, but I have set it as VARCHAR because one of the record value = 'X' for Unknown / Inapplicable entries.
	behaviour_coded_desc	varchar(60),	
	histology_coded			varchar(10),
	histology_coded_desc	varchar(70),
	grade					varchar(5),
	tumoursize				NUMERIC,
	nodesexcised			int,
	nodesinvolved			int,
	tumourcount				int,
	bigtumourcount			int,
	stage_best				varchar(10),
	t_best					varchar(10),
	n_best					varchar(10),
	m_best					varchar(10),
	stage_best_system		varchar(10),
	t_img					varchar(5),
	n_img					varchar(5),
	m_img					varchar(5),
	stage_img				varchar(5),
	stage_img_system		smallint,
	t_path					varchar(5),
	n_path					varchar(5),
	m_path					varchar(5),
	stage_path				varchar(5),
	stage_path_system		smallint,
	stage_path_pretreated	varchar(5),
	chrl_tot_27_03			int,
	chrl_tot_78_06			int,
	gleason_primary			smallint,
	gleason_secondary		smallint,
	gleason_tertiary		smallint,
	gleason_combined		smallint,
	dco						varchar(5),
	vitalstatus				varchar(15),
	vitalstatusdate			date
)
TABLESPACE pg_default;

--------------Creating treatment Table ---------------------------------------
CREATE TABLE IF NOT EXISTS {SOURCE_SCHEMA}.treatment (
	treatment_id			bigserial,		--to allow for a PK
	e_patid					bigint,
	e_cr_id					bigint,
	e_cr_patid				bigint,
	number_of_tumours		int,
	eventcode				varchar(5),
	eventdesc				varchar(40),
	eventdate				date,
	within_six_months_flag	smallint,
	six_months_after_flag	smallint,
	opcs4_code				varchar(10),
	opcs4_name				varchar(150),
	radiocode				varchar(5),
	radiodesc				varchar(30),
	lesionsize				NUMERIC,
	chemo_all_drug			varchar(50),
	chemo_drug_group		varchar(50)
)
TABLESPACE pg_default;

--------------Creating RTDS Table ---------------------------------------
CREATE TABLE IF NOT EXISTS {SOURCE_SCHEMA}.rtds (
	e_patid						bigint,
	e_cr_patid					bigint,
	e_cr_id						bigint,
	attendid					bigint,
	prescriptionid				bigint,
	apptdate					date,
	treatmentstartdate			date,
	radiotherapydiagnosisicd	varchar(7),
	radiotherapyintent			varchar(2),
	rttreatmentregion			varchar(2),
	rttreatmentanatomicalsite	varchar(30),
	numberofteletherapyfields	smallint,
	rtprescribeddose			double precision,
	prescribedfractions			smallint,
	rtactualdose				double precision,
	actualfractions				smallint,
	rttreatmentmodality			varchar(2),
	radiotherapybeamtype		varchar(2),
	radiotherapybeamenergy		double precision,
	primaryprocedureopcs		varchar(4),
	proceduredate				date
)
TABLESPACE pg_default;

--------------Creating SACT Table ---------------------------------------
CREATE TABLE IF NOT EXISTS {SOURCE_SCHEMA}.sact (
	e_patid							bigint,
	e_cr_patid						bigint,
	e_cr_id							bigint,
	pseudo_merged_tumour_id			bigint,
	primary_diagnosis				varchar(7),
	morphology_clean				varchar(7),
	height_at_start_of_regimen		double precision,
	weight_at_start_of_regimen		double precision,
	intent_of_treatment				varchar(2),
	adjunctive_therapy				smallint,
	analysis_group					varchar(59),
	benchmark_group					varchar(59),
	perf_status_start_of_regimen	varchar(2),
	perf_stat_start_of_reg_adult	varchar(2),
	perf_stat_start_of_reg_child	varchar(2),
	comorbidity_adjustment			varchar(1),
	date_decision_to_treat			date,
	start_date_of_regimen			date,
	cycle_number					smallint,
	start_date_of_cycle				date,
	perf_stat_start_of_cycle_clean	varchar(1),
	perf_stat_start_of_cycle_adult	varchar(1),
	perf_stat_start_of_cycle_child	varchar(1),
	weight_at_start_of_cycle		double precision,
	drug_group						varchar(35),
	actual_dose_per_administration	double precision,
	admin_measure_per_actual_dose	varchar(2),
	administration_route			varchar(2),
	administration_date				date,
	regimen_modification_dose_red	varchar(1),
	regoutsum_cur_not_com_plan		varchar(1),
	regoutsum_non_curat				varchar(1),
	regoutsum_toxic					varchar(1),
	regoutsum_cur_com_plan			varchar(1)
)
TABLESPACE pg_default;
