--CREATE TABLE IF NOT EXISTS {SOURCE_SCHEMA}.linkage_coverage
--(
--	data_source varchar(10) NOT NULL,
--	"start" DATE NOT NULL,
--	"end" DATE NOT NULL
--)TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS {SOURCE_SCHEMA}.ons_death (
	patid				bigint,
	pracid				int,
--	gen_death_id		bigint,
--	n_patid_death		int,
--	match_rank			int,
--	dor					date,
--	dod					date,
--	dod_partial			varchar(10),
--	nhs_indicator		int,
--	pod_category		varchar(25),
--	cause				varchar(6),
--	cause1				varchar(6),
--	cause2				varchar(6),
--	cause3				varchar(6),
--	cause4				varchar(6),
--	cause5				varchar(6),
--	cause6				varchar(6),
--	cause7				varchar(6),
--	cause8				varchar(6),
--	cause9				varchar(6),
--	cause10				varchar(6),
--	cause11				varchar(6),
--	cause12				varchar(6),
--	cause13				varchar(6),
--	cause14				varchar(6),
--	cause15				varchar(6),
--	cause_neonatal1		varchar(6),
--	cause_neonatal2		varchar(6),
--	cause_neonatal3		varchar(6),
--	cause_neonatal4		varchar(6),
--	cause_neonatal5		varchar(6),
--	cause_neonatal6		varchar(6),
--	cause_neonatal7		varchar(6),
--	cause_neonatal8		varchar(6)
	icd9_orig_mention_1	varchar(6),
	icd9_orig_mention_2	varchar(6),
	icd9_orig_mention_3	varchar(6),
	icd9_orig_mention_4	varchar(6),
	icd9_orig_mention_5	varchar(6),
	icd9_orig_mention_6	varchar(6),
	icd9_orig_mention_7	varchar(6),
	icd9_orig_mention_8	varchar(6),
	icd9_orig_mention_9	varchar(6),
	icd9_orig_mention_10	varchar(6),
	icd9_orig_mention_11	varchar(6),
	icd9_orig_mention_12	varchar(6),
	icd9_orig_mention_13	varchar(6),
	icd9_orig_mention_14	varchar(6),
	icd9_orig_mention_15	varchar(6),
	neo_nate_flag	int,
	pod_code	varchar(20),
	pod_establishment_type	varchar(6),
	pod_nhs_establishment	int,
	reg_date	date,
	reg_date_of_death	date,
	s_cod_code_1	varchar(6),
	s_cod_code_2	varchar(6),
	s_cod_code_3	varchar(6),
	s_cod_code_4	varchar(6),
	s_cod_code_5	varchar(6),
	s_cod_code_6	varchar(6),
	s_cod_code_7	varchar(6),
	s_cod_code_8	varchar(6),
	s_cod_code_9	varchar(6),
	s_cod_code_10	varchar(6),
	s_cod_code_11	varchar(6),
	s_cod_code_12	varchar(6),
	s_cod_code_13	varchar(6),
	s_cod_code_14	varchar(6),
	s_cod_code_15	varchar(6),
	s_underlying_cod_icd10	varchar(6),
	s_underlying_cod_icd9	varchar(6)
)TABLESPACE pg_default;