ALTER TABLE {SOURCE_SCHEMA}.staff ADD CONSTRAINT pk_staff PRIMARY KEY(staffid) USING INDEX TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_staff_role ON {SOURCE_SCHEMA}.staff(role) TABLESPACE pg_default;
