DROP TABLE IF EXISTS {SOURCE_SCHEMA}.batchnumber CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.bnfcodes CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.common_dosages CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.entity CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.lookup CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.lookuptype CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.medical CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.packtype CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.product CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.scoremethod CASCADE;

