DROP TABLE IF EXISTS {SOURCE_SCHEMA}.lookup626 CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.gold_product CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.gold_daysupply_decodes CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.gold_daysupply_modes CASCADE;