DROP TABLE IF EXISTS {SOURCE_SCHEMA}.lookup269 CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.lookup270 CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.lookup626 CASCADE;
DROP TABLE IF EXISTS {SOURCE_SCHEMA}.lookup10 CASCADE;

