ALTER TABLE {VOCABULARY_SCHEMA}.DOMAIN ADD CONSTRAINT xpk_domain PRIMARY KEY (domain_id);

CREATE UNIQUE INDEX idx_domain_domain_id  ON {VOCABULARY_SCHEMA}.DOMAIN  (domain_id ASC);
CLUSTER {VOCABULARY_SCHEMA}.DOMAIN  USING idx_domain_domain_id ;