ALTER TABLE {VOCABULARY_SCHEMA}.VOCABULARY ADD CONSTRAINT xpk_vocabulary PRIMARY KEY (vocabulary_id) USING INDEX TABLESPACE pg_default;

CREATE UNIQUE INDEX idx_vocabulary_vocabulary_id  ON {VOCABULARY_SCHEMA}.VOCABULARY (vocabulary_id ASC) TABLESPACE pg_default;
CLUSTER {VOCABULARY_SCHEMA}.VOCABULARY USING idx_vocabulary_vocabulary_id;
