COPY {VOCABULARY_SCHEMA}.source_to_concept_map FROM '{STCM_DIRECTORY}\AURUM_JOB_CATEGORY_STCM.csv' WITH DELIMITER E',' CSV HEADER QUOTE E'"';

COPY {VOCABULARY_SCHEMA}.source_to_concept_map FROM '{STCM_DIRECTORY}\AURUM_ROUTE_STCM.csv' WITH DELIMITER E',' CSV HEADER QUOTE E'"';

COPY {VOCABULARY_SCHEMA}.source_to_concept_map FROM '{STCM_DIRECTORY}\AURUM_UNIT_STCM.csv' WITH DELIMITER E',' CSV HEADER QUOTE E'"';

-- COPY {VOCABULARY_SCHEMA}.source_to_concept_map FROM '{STCM_DIRECTORY}\CONSULTATION_STCM.csv' WITH DELIMITER E',' CSV HEADER QUOTE E'"';

