COPY {TARGET_SCHEMA}.source_to_concept_map FROM '{STCM_DIRECTORY}\GOLD_ADD_ETYPE_STCM.csv' WITH DELIMITER E',' CSV HEADER QUOTE E'"';

COPY {TARGET_SCHEMA}.source_to_concept_map FROM '{STCM_DIRECTORY}\GOLD_TEST_ETYPE_STCM.csv' WITH DELIMITER E',' CSV HEADER QUOTE E'"';

COPY {TARGET_SCHEMA}.source_to_concept_map FROM '{STCM_DIRECTORY}\GOLD_UNIT_STCM.csv' WITH DELIMITER E',' CSV HEADER QUOTE E'"';

-- COPY {TARGET_SCHEMA}.source_to_concept_map FROM '{STCM_DIRECTORY}\GOLD_ROUTE_STCM.csv' WITH DELIMITER E',' CSV HEADER QUOTE E'"';