ALTER TABLE {TARGET_SCHEMA}.NOTE ADD CONSTRAINT fpk_NOTE_note_type_concept_id FOREIGN KEY (note_type_concept_id) REFERENCES {TARGET_SCHEMA}.CONCEPT (CONCEPT_ID);
ALTER TABLE {TARGET_SCHEMA}.NOTE ADD CONSTRAINT fpk_NOTE_note_class_concept_id FOREIGN KEY (note_class_concept_id) REFERENCES {TARGET_SCHEMA}.CONCEPT (CONCEPT_ID);
ALTER TABLE {TARGET_SCHEMA}.NOTE ADD CONSTRAINT fpk_NOTE_encoding_concept_id FOREIGN KEY (encoding_concept_id) REFERENCES {TARGET_SCHEMA}.CONCEPT (CONCEPT_ID);
ALTER TABLE {TARGET_SCHEMA}.NOTE ADD CONSTRAINT fpk_NOTE_language_concept_id FOREIGN KEY (language_concept_id) REFERENCES {TARGET_SCHEMA}.CONCEPT (CONCEPT_ID);
