-- FKs specific for cdm 5.4;
ALTER TABLE {TARGET_SCHEMA}.DEVICE_EXPOSURE ADD CONSTRAINT fpk_DEVICE_EXPOSURE_unit_concept_id FOREIGN KEY (unit_concept_id) REFERENCES {VOCABULARY_SCHEMA}.CONCEPT (CONCEPT_ID);
ALTER TABLE {TARGET_SCHEMA}.DEVICE_EXPOSURE ADD CONSTRAINT fpk_DEVICE_EXPOSURE_unit_source_concept_id FOREIGN KEY (unit_source_concept_id) REFERENCES {VOCABULARY_SCHEMA}.CONCEPT (CONCEPT_ID);

ALTER TABLE {TARGET_SCHEMA}.MEASUREMENT ADD CONSTRAINT fpk_MEASUREMENT_unit_source_concept_id FOREIGN KEY (unit_source_concept_id) REFERENCES {VOCABULARY_SCHEMA}.CONCEPT (CONCEPT_ID);
ALTER TABLE {TARGET_SCHEMA}.MEASUREMENT ADD CONSTRAINT fpk_MEASUREMENT_meas_event_field_concept_id FOREIGN KEY (meas_event_field_concept_id) REFERENCES {VOCABULARY_SCHEMA}.CONCEPT (CONCEPT_ID);

ALTER TABLE {TARGET_SCHEMA}.OBSERVATION ADD CONSTRAINT fpk_OBSERVATION_obs_event_field_concept_id FOREIGN KEY (obs_event_field_concept_id) REFERENCES {VOCABULARY_SCHEMA}.CONCEPT (CONCEPT_ID);

ALTER TABLE {TARGET_SCHEMA}.LOCATION ADD CONSTRAINT fpk_LOCATION_country_concept_id FOREIGN KEY (country_concept_id) REFERENCES {VOCABULARY_SCHEMA}.CONCEPT (CONCEPT_ID);

ALTER TABLE {TARGET_SCHEMA}.CDM_SOURCE ADD CONSTRAINT fpk_CDM_SOURCE_cdm_version_concept_id FOREIGN KEY (cdm_version_concept_id) REFERENCES {VOCABULARY_SCHEMA}.CONCEPT (CONCEPT_ID);